export const CONNECTION_ERROR = "Sorry, Can not connect to server !"
export const SERVER_ERROR = "Sorry, An unknown error occur !"
export const BASE_URL = "http://localhost:8000"
// export const BASE_URL = "https://impossible-crab-tunic.cyclic.app/api"
export const DEFAULT_PROFILE_IMG = "http://localhost:3001/api"
export const MY_IMG = "https://res.cloudinary.com/dhyc0vsbz/image/upload/w_510,h_360,c_fill/v1665951550/l2zq8kjqu9nywwoeofzf.jpg"
